### ISSUE TITLE
stm32F746 disco - lcd demo wont compile

### ISSUE THREAD

**Issue by ghost** [ChrisMicro/Arduino_STM32F7_Discovery#1]
I'm getting the follwoing error when compiling the LCD demo.ino
LTDC_HandleTypeDef' does not name a type
Any suggestions 
Ta

**Comment by ChrisMicro** [comment]
Did you install this Arduino framework:
https://github.com/ChrisMicro/STM32GENERIC

**Comment by ghost** [comment]
Yes I did. Will look into it again now that I have had some sleep :-)

**Comment by ghost** [comment]
Here is the complete error code:

Arduino: 1.8.1 (Windows 10), Board: "Discovery, STM32F746G-DISCOVERY, Mass Storage, None, None"

C:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -hardware C:\Users\Kim\AppData\Local\Arduino15\packages -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\Kim\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\Kim\Documents\Arduino\libraries -fqbn=STM32:stm32:Disco:board_part_num=DISCO_F746NG,upload_method=MassStorageMethod,Other_serial=enable_Serial,USB_interface=enable_USB -ide-version=10801 -build-path C:\Users\Kim\AppData\Local\Temp\arduino_build_485538 -warnings=all -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.arm-none-eabi-gcc.path=C:\Users\Kim\AppData\Local\Arduino15\packages\STM32\tools\arm-none-eabi-gcc\6-2017-q1-update -prefs=runtime.tools.CMSIS.path=C:\Users\Kim\AppData\Local\Arduino15\packages\arduino\tools\CMSIS\4.5.0 -prefs=runtime.tools.STM32Tools.path=C:\Users\Kim\AppData\Local\Arduino15\packages\STM32\tools\STM32Tools\2017.8.31 -verbose C:\Users\Kim\Desktop\STM32GENERIC-master\STM32\libraries\BoardExamples\examples\Discovery746NG\TFT\Demo\Demo.ino
C:\Program Files (x86)\Arduino\arduino-builder -compile -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -hardware C:\Users\Kim\AppData\Local\Arduino15\packages -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\Kim\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\Kim\Documents\Arduino\libraries -fqbn=STM32:stm32:Disco:board_part_num=DISCO_F746NG,upload_method=MassStorageMethod,Other_serial=enable_Serial,USB_interface=enable_USB -ide-version=10801 -build-path C:\Users\Kim\AppData\Local\Temp\arduino_build_485538 -warnings=all -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.arm-none-eabi-gcc.path=C:\Users\Kim\AppData\Local\Arduino15\packages\STM32\tools\arm-none-eabi-gcc\6-2017-q1-update -prefs=runtime.tools.CMSIS.path=C:\Users\Kim\AppData\Local\Arduino15\packages\arduino\tools\CMSIS\4.5.0 -prefs=runtime.tools.STM32Tools.path=C:\Users\Kim\AppData\Local\Arduino15\packages\STM32\tools\STM32Tools\2017.8.31 -verbose C:\Users\Kim\Desktop\STM32GENERIC-master\STM32\libraries\BoardExamples\examples\Discovery746NG\TFT\Demo\Demo.ino
Using board 'Disco' from platform in folder: C:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31
Using core 'arduino' from platform in folder: C:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31
Detecting libraries used...
"C:\Users\Kim\AppData\Local\Arduino15\packages\STM32\tools\arm-none-eabi-gcc\6-2017-q1-update/bin/arm-none-eabi-g++" -mthumb -c -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf  "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\cores\arduino/avr" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\cores\arduino/stm32" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Drivers/STM32F7xx_HAL_Driver/Inc/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Drivers/STM32F7xx_HAL_Driver/Src/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/STM32F7xx/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\variants\DISCO_F746NG/usb" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\variants\DISCO_F746NG/Ethernet" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -w -x c++ -E -CC -mcpu=cortex-m7 -DF_CPU=216000000L -DSTM32F7xx -DARDUINO=10801 -DARDUINO_DISCO_F746NG -DARDUINO_ARCH_STM32  -DSTM32F746xx   "-IC:\Users\Kim\AppData\Local\Arduino15\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Drivers/CMSIS/Device/ST/STM32F7xx/Include/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Drivers/CMSIS/Device/ST/STM32F7xx/Source/Templates/gcc/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\cores\arduino" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\variants\DISCO_F746NG" "C:\Users\Kim\AppData\Local\Temp\arduino_build_485538\sketch\Demo.ino.cpp" -o "nul"
"C:\Users\Kim\AppData\Local\Arduino15\packages\STM32\tools\arm-none-eabi-gcc\6-2017-q1-update/bin/arm-none-eabi-g++" -mthumb -c -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf  "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\cores\arduino/avr" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\cores\arduino/stm32" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Drivers/STM32F7xx_HAL_Driver/Inc/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Drivers/STM32F7xx_HAL_Driver/Src/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/STM32F7xx/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\variants\DISCO_F746NG/usb" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\variants\DISCO_F746NG/Ethernet" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -w -x c++ -E -CC -mcpu=cortex-m7 -DF_CPU=216000000L -DSTM32F7xx -DARDUINO=10801 -DARDUINO_DISCO_F746NG -DARDUINO_ARCH_STM32  -DSTM32F746xx   "-IC:\Users\Kim\AppData\Local\Arduino15\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Drivers/CMSIS/Device/ST/STM32F7xx/Include/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Drivers/CMSIS/Device/ST/STM32F7xx/Source/Templates/gcc/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\cores\arduino" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\variants\DISCO_F746NG" "-IC:\Users\Kim\Documents\Arduino\libraries\Adafruit_GFX_Library" "C:\Users\Kim\AppData\Local\Temp\arduino_build_485538\sketch\Demo.ino.cpp" -o "nul"
"C:\Users\Kim\AppData\Local\Arduino15\packages\STM32\tools\arm-none-eabi-gcc\6-2017-q1-update/bin/arm-none-eabi-g++" -mthumb -c -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf  "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\cores\arduino/avr" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\cores\arduino/stm32" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Drivers/STM32F7xx_HAL_Driver/Inc/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Drivers/STM32F7xx_HAL_Driver/Src/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/STM32F7xx/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\variants\DISCO_F746NG/usb" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\variants\DISCO_F746NG/Ethernet" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -w -x c++ -E -CC -mcpu=cortex-m7 -DF_CPU=216000000L -DSTM32F7xx -DARDUINO=10801 -DARDUINO_DISCO_F746NG -DARDUINO_ARCH_STM32  -DSTM32F746xx   "-IC:\Users\Kim\AppData\Local\Arduino15\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Drivers/CMSIS/Device/ST/STM32F7xx/Include/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Drivers/CMSIS/Device/ST/STM32F7xx/Source/Templates/gcc/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\cores\arduino" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\variants\DISCO_F746NG" "-IC:\Users\Kim\Documents\Arduino\libraries\Adafruit_GFX_Library" "C:\Users\Kim\Documents\Arduino\libraries\Adafruit_GFX_Library\Adafruit_GFX.cpp" -o "nul"
"C:\Users\Kim\AppData\Local\Arduino15\packages\STM32\tools\arm-none-eabi-gcc\6-2017-q1-update/bin/arm-none-eabi-g++" -mthumb -c -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf  "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\cores\arduino/avr" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\cores\arduino/stm32" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Drivers/STM32F7xx_HAL_Driver/Inc/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Drivers/STM32F7xx_HAL_Driver/Src/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/STM32F7xx/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\variants\DISCO_F746NG/usb" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\variants\DISCO_F746NG/Ethernet" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -w -x c++ -E -CC -mcpu=cortex-m7 -DF_CPU=216000000L -DSTM32F7xx -DARDUINO=10801 -DARDUINO_DISCO_F746NG -DARDUINO_ARCH_STM32  -DSTM32F746xx   "-IC:\Users\Kim\AppData\Local\Arduino15\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Drivers/CMSIS/Device/ST/STM32F7xx/Include/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Drivers/CMSIS/Device/ST/STM32F7xx/Source/Templates/gcc/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\cores\arduino" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\variants\DISCO_F746NG" "-IC:\Users\Kim\Documents\Arduino\libraries\Adafruit_GFX_Library" "C:\Users\Kim\Documents\Arduino\libraries\Adafruit_GFX_Library\glcdfont.c" -o "nul"
Generating function prototypes...
"C:\Users\Kim\AppData\Local\Arduino15\packages\STM32\tools\arm-none-eabi-gcc\6-2017-q1-update/bin/arm-none-eabi-g++" -mthumb -c -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf  "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\cores\arduino/avr" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\cores\arduino/stm32" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Drivers/STM32F7xx_HAL_Driver/Inc/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Drivers/STM32F7xx_HAL_Driver/Src/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/STM32F7xx/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\variants\DISCO_F746NG/usb" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\variants\DISCO_F746NG/Ethernet" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -w -x c++ -E -CC -mcpu=cortex-m7 -DF_CPU=216000000L -DSTM32F7xx -DARDUINO=10801 -DARDUINO_DISCO_F746NG -DARDUINO_ARCH_STM32  -DSTM32F746xx   "-IC:\Users\Kim\AppData\Local\Arduino15\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Drivers/CMSIS/Device/ST/STM32F7xx/Include/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Drivers/CMSIS/Device/ST/STM32F7xx/Source/Templates/gcc/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\cores\arduino" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\variants\DISCO_F746NG" "-IC:\Users\Kim\Documents\Arduino\libraries\Adafruit_GFX_Library" "C:\Users\Kim\AppData\Local\Temp\arduino_build_485538\sketch\Demo.ino.cpp" -o "C:\Users\Kim\AppData\Local\Temp\arduino_build_485538\preproc\ctags_target_for_gcc_minus_e.cpp"
"C:\Program Files (x86)\Arduino\tools-builder\ctags\5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\Users\Kim\AppData\Local\Temp\arduino_build_485538\preproc\ctags_target_for_gcc_minus_e.cpp"
Compiling sketch...
"C:\Users\Kim\AppData\Local\Arduino15\packages\STM32\tools\arm-none-eabi-gcc\6-2017-q1-update/bin/arm-none-eabi-g++" -mthumb -c -Os -Wall -Wextra -std=gnu++11 -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -MMD "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\cores\arduino/avr" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\cores\arduino/stm32" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Drivers/STM32F7xx_HAL_Driver/Inc/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Drivers/STM32F7xx_HAL_Driver/Src/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/STM32F7xx/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\variants\DISCO_F746NG/usb" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\variants\DISCO_F746NG/Ethernet" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Middlewares/ST/STM32_USB_Device_Library/Core/Src" -mcpu=cortex-m7 -DF_CPU=216000000L -DSTM32F7xx -DARDUINO=10801 -DARDUINO_DISCO_F746NG -DARDUINO_ARCH_STM32  -DSTM32F746xx   "-IC:\Users\Kim\AppData\Local\Arduino15\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Drivers/CMSIS/Device/ST/STM32F7xx/Include/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\system/Drivers/CMSIS/Device/ST/STM32F7xx/Source/Templates/gcc/" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\cores\arduino" "-IC:\Users\Kim\AppData\Local\Arduino15\packages\STM32\hardware\stm32\2017.8.31\variants\DISCO_F746NG" "-IC:\Users\Kim\Documents\Arduino\libraries\Adafruit_GFX_Library" "C:\Users\Kim\AppData\Local\Temp\arduino_build_485538\sketch\Demo.ino.cpp" -o "C:\Users\Kim\AppData\Local\Temp\arduino_build_485538\sketch\Demo.ino.cpp.o"
In file included from C:\Users\KIM\AppData\Local\Temp\arduino_build_485538\sketch\LTDC_F746_Discovery.h:6:0,

                 from C:\Users\Kim\Desktop\STM32GENERIC-master\STM32\libraries\BoardExamples\examples\Discovery746NG\TFT\Demo\Demo.ino:12:

LTDC.h:97: error: 'LTDC_HandleTypeDef' does not name a type

         LTDC_HandleTypeDef hLtdcHandler;

         ^~~~~~~~~~~~~~~~~~

C:\Users\Kim\AppData\Local\Temp\arduino_build_485538\sketch\LTDC.h: In member function 'void LTDCClass<W, H>::begin(uint16_t*)':

LTDC.h:105: error: 'hLtdcHandler' was not declared in this scope

     hLtdcHandler.Init.HorizontalSync = (settings.horizontalSync - 1);

     ^~~~~~~~~~~~

In file included from C:\Users\Kim\AppData\Local\Temp\arduino_build_485538\sketch\LTDC_F746_Discovery.h:6:0,

                 from C:\Users\Kim\Desktop\STM32GENERIC-master\STM32\libraries\BoardExamples\examples\Discovery746NG\TFT\Demo\Demo.ino:12:

LTDC.h:126: error: 'LTDC_HSPOLARITY_AL' was not declared in this scope

     hLtdcHandler.Init.HSPolarity = LTDC_HSPOLARITY_AL;

                                    ^~~~~~~~~~~~~~~~~~

LTDC.h:127: error: 'LTDC_VSPOLARITY_AL' was not declared in this scope

     hLtdcHandler.Init.VSPolarity = LTDC_VSPOLARITY_AL;

                                    ^~~~~~~~~~~~~~~~~~

LTDC.h:128: error: 'LTDC_DEPOLARITY_AL' was not declared in this scope

     hLtdcHandler.Init.DEPolarity = LTDC_DEPOLARITY_AL;

                                    ^~~~~~~~~~~~~~~~~~

LTDC.h:129: error: 'LTDC_PCPOLARITY_IPC' was not declared in this scope

     hLtdcHandler.Init.PCPolarity = LTDC_PCPOLARITY_IPC;

                                    ^~~~~~~~~~~~~~~~~~~

LTDC.h:136: error: there are no arguments to 'HAL_LTDC_Init' that depend on a template parameter, so a declaration of 'HAL_LTDC_Init' must be available [-fpermissive]

     HAL_LTDC_Init(&hLtdcHandler);

                                ^

C:\Users\Kim\AppData\Local\Temp\arduino_build_485538\sketch\LTDC.h:136:32: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)

LTDC.h:138: error: 'LTDC_LayerCfgTypeDef' was not declared in this scope

     LTDC_LayerCfgTypeDef  layer_cfg;

     ^~~~~~~~~~~~~~~~~~~~

LTDC.h:141: error: 'layer_cfg' was not declared in this scope

     layer_cfg.WindowX0 = 0;

     ^~~~~~~~~

LTDC.h:145: error: 'LTDC_PIXEL_FORMAT_RGB565' was not declared in this scope

     layer_cfg.PixelFormat = LTDC_PIXEL_FORMAT_RGB565;

                             ^~~~~~~~~~~~~~~~~~~~~~~~

LTDC.h:152: error: 'LTDC_BLENDING_FACTOR1_PAxCA' was not declared in this scope

     layer_cfg.BlendingFactor1 = LTDC_BLENDING_FACTOR1_PAxCA;

                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~

LTDC.h:153: error: 'LTDC_BLENDING_FACTOR2_PAxCA' was not declared in this scope

     layer_cfg.BlendingFactor2 = LTDC_BLENDING_FACTOR2_PAxCA;

                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~

LTDC.h:157: error: there are no arguments to 'HAL_LTDC_ConfigLayer' that depend on a template parameter, so a declaration of 'HAL_LTDC_ConfigLayer' must be available [-fpermissive]

     HAL_LTDC_ConfigLayer(&hLtdcHandler, &layer_cfg, 0);

                                                      ^

In file included from C:\Users\Kim\Desktop\STM32GENERIC-master\STM32\libraries\BoardExamples\examples\Discovery746NG\TFT\Demo\Demo.ino:12:0:

C:\Users\Kim\AppData\Local\Temp\arduino_build_485538\sketch\LTDC_F746_Discovery.h: In member function 'virtual void LTDC_F746_Discovery::init()':

LTDC_F746_Discovery.h:83: error: 'PI12' was not declared in this scope

         pinMode(PI12, OUTPUT);

                 ^~~~

LTDC_F746_Discovery.h:87: error: 'PK3' was not declared in this scope

         pinMode(PK3, OUTPUT);

                 ^~~

In file included from C:\Users\Kim\AppData\Local\Temp\arduino_build_485538\sketch\LTDC_F746_Discovery.h:6:0,

                 from C:\Users\Kim\Desktop\STM32GENERIC-master\STM32\libraries\BoardExamples\examples\Discovery746NG\TFT\Demo\Demo.ino:12:

C:\Users\Kim\AppData\Local\Temp\arduino_build_485538\sketch\LTDC.h: In instantiation of 'void LTDCClass<W, H>::begin(uint16_t*) [with int W = 480; int H = 272; uint16_t = short unsigned int]':

C:\Users\Kim\Desktop\STM32GENERIC-master\STM32\libraries\BoardExamples\examples\Discovery746NG\TFT\Demo\Demo.ino:24:31:   required from here

LTDC.h:136: error: 'HAL_LTDC_Init' was not declared in this scope

     HAL_LTDC_Init(&hLtdcHandler);

                                ^

LTDC.h:157: error: 'HAL_LTDC_ConfigLayer' was not declared in this scope

     HAL_LTDC_ConfigLayer(&hLtdcHandler, &layer_cfg, 0);

     ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Using library Adafruit_GFX_Library at version 1.2.2 in folder: C:\Users\Kim\Documents\Arduino\libraries\Adafruit_GFX_Library 
exit status 1
'LTDC_HandleTypeDef' does not name a type

**Comment by ChrisMicro** [comment]
I think it is a path problem.
You have installed the STM32GENERIC in
C:\Users\Kim\AppData\Local\Arduino15\packages\STM32
My Arduino-IDE 1.8 is installed in
C:/Tools/Arduino/Arduino1_8
I have copied the STM32GENERIC repository into the Arduino IDE folder
C:/Tools/Arduino/Arduino1_8/hardware/STM32GENERIC
So: If you move the repository from the Arduino15 folder into the Arduino IDE hardware folder, it should work.

**Comment by florinbaciuu** [comment]
Hello. Navigate to folder:   (Where "USER" is your username) :
C:\Users\""USER""\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.5.0\variants\STM32F7xx\F746B(E-G)T_F746N(E-G)H_F750N8H_F756BGT_F756NGH... 
(this is for stm32duino core). For other core navigate to variants folder of "that" board.


There you will find a file named: variant_DISCO_F746NG.h.
Open this file with a text editor and add this text in a new line :
"#define HAL_LTDC_MODULE_ENABLED" 

Then save it.
Recompile and thats it. 
This will enable the LTDC module .
